### PR TITLE
XDOCKBUILD-20: Introduce a jenkins agent image for node projects

### PR DESCRIPTION
**Pull request by manuelleduc**

### CODE REVIEW

**Comment by vmassol** [comment]
Sounds good. Missing some update at https://github.com/xwiki/xwiki-docker-build/blob/e2fa0aee77ba73e687e5eaaeaddbdbb38ad37cbb/.github/workflows/build.yml#L21

**Comment by vmassol** [comment]
the only comment I have is that we don't necessarily need to build the two images at the same time but why not.

**Comment by vmassol** [comment]
Another comment: the image is not just for jenkins. It's for building any project with node (locally, on CI, elsewhere)

**Comment by manuelleduc** [comment]
> the only comment I have is that we don't necessarily need to build the two images at the same time but why not.

Good point, I'm not really familiar with Github actions. I'll check how to decouple the two builds.

**Comment by vmassol** [comment]
> Good point, I'm not really familiar with Github actions. I'll check how to decouple the two builds.

Not sure you need to do that. Was just raising it as a possibility. You'd need a different trigger. This can be achieved with a different yml file but it'll mean lots of duplications too so not sure it's better.

**Review by vmassol — APPROVED** [review]

**Pull request merged**
